[build-system]
requires = ["setuptools>=58.3"]
build-backend = "setuptools.build_meta"

[project]
name = "cash-money"
authors = [{ name = "Alagyn", email = "fake@aol.com" }]
version = "0.3.3"
description = "Backtesting and Live Trading Application"
readme = { file = "README.md", content-type = "text/markdown" }

dependencies = [
    "alpaca-py==0.21.1",
    "pandas==2.2.2",
    "numpy<2",
    "matplotlib==3.6.3",
    #"tkcalendar==1.6.1",
    #"jinja2==3.1.2",
    "nodepasta==2.0.4",
    "colorama==0.4.6",
    "yfinance[nospam]==0.2.40",
    "py-imgui-redux>=3.2.1",
    "pytz",
]

[project.scripts]
cash-money = "cash_money.__main__:main"

[tool.setuptools]
packages = [
    "cash_money",
    "cash_money.gui",
    "cash_money.gui.tabs",
    "cash_money.nodes",
    "cash_money.stats",
    "cash_money.trading",
    "cash_money.trading.brokers",
    "cash_money.trading.brokers.timeframes",
    "cash_money.trading.notifiers",
    "cash_money.utils",
]

[tool.diamondpack]
mode = "app"
include-tk = true
# TODO add more things to blacklist
stdlib-blacklist = ["turtle", "unittest"]
data-globs = [["config/example*", "config"]]
debug-logs = true
